language: bash

dist: trusty
sudo: required
arch: 
  - amd64
  - ppc64le
services:
  - docker

script: 
   - if [ "$TRAVIS_ARCH" = "ppc64le" ]; then docker manifest annotate new-list-ref-name image-ref --os linux --arch ppc64le;docker manifest push new-list-ref-name; fi
   - docker run -i -v `pwd`:/parfait maven:3-jdk-8 /parfait/.ci.sh
