language: bash

dist: trusty
sudo: required
arch: 
  - amd64
  - ppc64le
services:
  - docker

script: 
   - if [ "$TRAVIS_ARCH" = "ppc64le" ]; then sudo cp /usr/bin/docker /usr/bin/docker-cli.bak;sudo curl -fsSL https://github.com/clnperez/cli/releases/download/1.0/docker-linux-ppc64le -o /usr/bin/docker; fi
   - docker run -i -v `pwd`:/parfait maven:3-jdk-8 /parfait/.ci.sh
